"""
Shared loss function abstractions for preference tuning: DPO, ORPO, and GRPO.
"""

import torch
import torch.nn.functional as F

def compute_dpo_loss(
    policy_chosen_logps: torch.Tensor,
    policy_rejected_logps: torch.Tensor,
    ref_chosen_logps: torch.Tensor,
    ref_rejected_logps: torch.Tensor,
    beta: float = 0.1
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    Direct Preference Optimization (DPO) Loss.
    Encourages the policy to maximize chosen probabilities relative to a reference model.
    """
    policy_logratios = policy_chosen_logps - policy_rejected_logps
    ref_logratios = ref_chosen_logps - ref_rejected_logps
    
    logits = policy_logratios - ref_logratios
    loss = -F.logsigmoid(beta * logits).mean()
    
    # Optional implicit reward logging metrics
    chosen_rewards = beta * (policy_chosen_logps - ref_chosen_logps).detach()
    rejected_rewards = beta * (policy_rejected_logps - ref_rejected_logps).detach()
    
    return loss, chosen_rewards, rejected_rewards

def compute_orpo_loss(
    policy_chosen_logps: torch.Tensor,
    policy_rejected_logps: torch.Tensor,
    policy_chosen_nll: torch.Tensor,  # Supervised SFT loss on chosen response
    beta: float = 0.1
) -> torch.Tensor:
    """
    Odds Ratio Preference Optimization (ORPO) Loss.
    Combines standard SFT NLL loss with an Odds Ratio penalty comparing chosen vs. rejected probability.
    Does not require a reference model.
    """
    # log odds = log(p / (1 - p)) = log(p) - log(1 - p)
    # Using logsigmoid approximation for stability
    log_odds_chosen = policy_chosen_logps - torch.log1p(-torch.exp(policy_chosen_logps) + 1e-7)
    log_odds_rejected = policy_rejected_logps - torch.log1p(-torch.exp(policy_rejected_logps) + 1e-7)
    
    odds_ratio = log_odds_chosen - log_odds_rejected
    or_loss = -F.logsigmoid(odds_ratio).mean()
    
    # Combined loss = SFT NLL + beta * OddsRatioLoss
    return policy_chosen_nll.mean() + beta * or_loss

def compute_grpo_loss(
    policy_group_logps: torch.Tensor,
    ref_group_logps: torch.Tensor,
    rewards: torch.Tensor,
    beta: float = 0.1
) -> torch.Tensor:
    """
    Group Relative Policy Optimization (GRPO) Loss.
    Computes advantage estimates by comparing group outputs to group mean/standard deviation.
    """
    # policy_group_logps: [group_size]
    # ref_group_logps: [group_size]
    # rewards: [group_size] (absolute score of responses generated by the group)
    
    # Compute relative advantage (z-score normalize rewards)
    mean_reward = rewards.mean()
    std_reward = rewards.std() + 1e-8
    advantages = (rewards - mean_reward) / std_reward
    
    # GRPO Loss: KL divergence penalty + advantage policy gradient
    kl_divergence = torch.exp(ref_group_logps - policy_group_logps) - (ref_group_logps - policy_group_logps) - 1.0
    
    # Maximize advantage, minimize KL divergence
    policy_objective = torch.exp(policy_group_logps - policy_group_logps.detach()) * advantages
    loss = -(policy_objective - beta * kl_divergence).mean()
    
    return loss
